package com.maiya.impl;

import com.maiya.bean.User;
import com.maiya.dao.UserMapper;
import com.maiya.service.UserService;
import org.springframework.stereotype.Service;

import javax.annotation.Resource;
import java.util.HashMap;
import java.util.List;

@Service("userService")
public class UserServiceImpl implements UserService {
	@Resource  
    private UserMapper userDao;
	
	public User selectByPassword(String name, String password) {
		return userDao.selectByPassword(name, password);
	}
	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbggenerated
     */
    public int deleteByPrimaryKey(Long id) {
    	return userDao.deleteByPrimaryKey(id);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbggenerated
     */
    public int insertSelective(User record) {
    	return userDao.insertSelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbggenerated
     */
    public User selectByPrimaryKey(Long id) {
    	return userDao.selectByPrimaryKey(id);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbggenerated
     */
    public int updateByPrimaryKeySelective(User record) {
    	return userDao.updateByPrimaryKeySelective(record);
    }

    public List<Object> selectAll(String name) {
        return userDao.selectAll(name);
    }

    public List<Object> selectAllByUserId(HashMap<String, Object> parameters) {
        return userDao.selectAllByUserId(parameters);
    }

    public User selectVerifyCodeByPhone(String phone_number) {
        return userDao.selectVerifyCodeByPhone(phone_number);
    }

    public int updateByPhone(User record) {
        return userDao.updateByPhone(record);
    }
}

