package com.maiya.controllers;

public class ProductTblDelete {
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.vendor_id
     *
     * @mbggenerated
     */
    private Long productId;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_tbl.vendor_id
     *
     * @return the value of product_tbl.vendor_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_tbl.vendor_id
     *
     * @param vendorId the value for product_tbl.vendor_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

}
