package com.maiya.dao;

import com.maiya.bean.Address;

public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int insert(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int insertSelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    Address selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int updateByPrimaryKeySelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int updateByPrimaryKey(Address record);
}