package com.maiya.dao;

import com.maiya.bean.Diagnosis;

public interface DiagnosisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnosis_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnosis_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int insert(Diagnosis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnosis_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int insertSelective(Diagnosis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnosis_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    Diagnosis selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnosis_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int updateByPrimaryKeySelective(Diagnosis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnosis_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Diagnosis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnosis_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int updateByPrimaryKey(Diagnosis record);
}