package com.maiya.dao;

import com.maiya.bean.Doctors;

public interface DoctorsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctors_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctors_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int insert(Doctors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctors_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int insertSelective(Doctors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctors_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    Doctors selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctors_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int updateByPrimaryKeySelective(Doctors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctors_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Doctors record);
}