package com.maiya.dao;

import com.maiya.bean.Knowlege;

public interface KnowlegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int insert(Knowlege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int insertSelective(Knowlege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    Knowlege selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int updateByPrimaryKeySelective(Knowlege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Knowlege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int updateByPrimaryKey(Knowlege record);
}