package com.maiya.dao;

import com.maiya.bean.Orders;

public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int insertSelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    Orders selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int updateByPrimaryKeySelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int updateByPrimaryKey(Orders record);
}