package com.maiya.dao;

import com.maiya.bean.Persontag;

public interface PersontagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persontag_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persontag_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int insert(Persontag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persontag_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int insertSelective(Persontag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persontag_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    Persontag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persontag_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int updateByPrimaryKeySelective(Persontag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persontag_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int updateByPrimaryKey(Persontag record);
}