package com.maiya.dao;

import com.maiya.bean.Promotion;
import java.util.List;

public interface PromotionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    int insert(Promotion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    int insertSelective(Promotion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    Promotion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    int updateByPrimaryKeySelective(Promotion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    int updateByPrimaryKey(Promotion record);

    int insertBatchSelective(List<Promotion> records);

    int updateBatchByPrimaryKeySelective(List<Promotion> records);
}