package com.maiya.dao;

import com.maiya.bean.Sets;
import java.util.List;

public interface SetsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sets_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sets_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    int insert(Sets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sets_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    int insertSelective(Sets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sets_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    Sets selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sets_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    int updateByPrimaryKeySelective(Sets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sets_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    int updateByPrimaryKey(Sets record);

    int insertBatchSelective(List<Sets> records);

    int updateBatchByPrimaryKeySelective(List<Sets> records);
}