package com.maiya.dao;

import com.maiya.bean.Sets;

public interface SetsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sets_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sets_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int insert(Sets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sets_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int insertSelective(Sets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sets_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    Sets selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sets_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int updateByPrimaryKeySelective(Sets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sets_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    int updateByPrimaryKey(Sets record);
}