package com.maiya.bean;

import java.io.Serializable;

public class Address implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_tbl.id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_tbl.user_id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_tbl.user_name
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_tbl.zip_code
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_tbl.phone
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_tbl.address
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_tbl.id
     *
     * @return the value of address_tbl.id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_tbl.id
     *
     * @param id the value for address_tbl.id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_tbl.user_id
     *
     * @return the value of address_tbl.user_id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_tbl.user_id
     *
     * @param userId the value for address_tbl.user_id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_tbl.user_name
     *
     * @return the value of address_tbl.user_name
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_tbl.user_name
     *
     * @param userName the value for address_tbl.user_name
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_tbl.zip_code
     *
     * @return the value of address_tbl.zip_code
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_tbl.zip_code
     *
     * @param zipCode the value for address_tbl.zip_code
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_tbl.phone
     *
     * @return the value of address_tbl.phone
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_tbl.phone
     *
     * @param phone the value for address_tbl.phone
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_tbl.address
     *
     * @return the value of address_tbl.address
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_tbl.address
     *
     * @param address the value for address_tbl.address
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Address other = (Address) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getZipCode() == null ? other.getZipCode() == null : this.getZipCode().equals(other.getZipCode()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getZipCode() == null) ? 0 : getZipCode().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", zipCode=").append(zipCode);
        sb.append(", phone=").append(phone);
        sb.append(", address=").append(address);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}