package com.maiya.bean;

import java.io.Serializable;

public class Diagnosis implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagnosis_tbl.id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagnosis_tbl.user_id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagnosis_tbl.notes
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagnosis_tbl.images
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private String images;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table diagnosis_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagnosis_tbl.id
     *
     * @return the value of diagnosis_tbl.id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagnosis_tbl.id
     *
     * @param id the value for diagnosis_tbl.id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagnosis_tbl.user_id
     *
     * @return the value of diagnosis_tbl.user_id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagnosis_tbl.user_id
     *
     * @param userId the value for diagnosis_tbl.user_id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagnosis_tbl.notes
     *
     * @return the value of diagnosis_tbl.notes
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagnosis_tbl.notes
     *
     * @param notes the value for diagnosis_tbl.notes
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagnosis_tbl.images
     *
     * @return the value of diagnosis_tbl.images
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagnosis_tbl.images
     *
     * @param images the value for diagnosis_tbl.images
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setImages(String images) {
        this.images = images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnosis_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Diagnosis other = (Diagnosis) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getNotes() == null ? other.getNotes() == null : this.getNotes().equals(other.getNotes()))
            && (this.getImages() == null ? other.getImages() == null : this.getImages().equals(other.getImages()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnosis_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getNotes() == null) ? 0 : getNotes().hashCode());
        result = prime * result + ((getImages() == null) ? 0 : getImages().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diagnosis_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", notes=").append(notes);
        sb.append(", images=").append(images);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}