package com.maiya.bean;

import java.io.Serializable;
import java.util.Date;

public class Knowlege implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_tbl.id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_tbl.writer
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private String writer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_tbl.title
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_tbl.create_time
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_tbl.content
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table knowledge_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_tbl.id
     *
     * @return the value of knowledge_tbl.id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_tbl.id
     *
     * @param id the value for knowledge_tbl.id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_tbl.writer
     *
     * @return the value of knowledge_tbl.writer
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public String getWriter() {
        return writer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_tbl.writer
     *
     * @param writer the value for knowledge_tbl.writer
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setWriter(String writer) {
        this.writer = writer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_tbl.title
     *
     * @return the value of knowledge_tbl.title
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_tbl.title
     *
     * @param title the value for knowledge_tbl.title
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_tbl.create_time
     *
     * @return the value of knowledge_tbl.create_time
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_tbl.create_time
     *
     * @param createTime the value for knowledge_tbl.create_time
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_tbl.content
     *
     * @return the value of knowledge_tbl.content
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_tbl.content
     *
     * @param content the value for knowledge_tbl.content
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Knowlege other = (Knowlege) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getWriter() == null ? other.getWriter() == null : this.getWriter().equals(other.getWriter()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getWriter() == null) ? 0 : getWriter().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", writer=").append(writer);
        sb.append(", title=").append(title);
        sb.append(", createTime=").append(createTime);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}