package com.maiya.bean;

import java.io.Serializable;

public class Persontag implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persontag_tbl.id
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persontag_tbl.user_id
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persontag_tbl.descs
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    private String descs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table persontag_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persontag_tbl.id
     *
     * @return the value of persontag_tbl.id
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persontag_tbl.id
     *
     * @param id the value for persontag_tbl.id
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persontag_tbl.user_id
     *
     * @return the value of persontag_tbl.user_id
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persontag_tbl.user_id
     *
     * @param userId the value for persontag_tbl.user_id
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persontag_tbl.descs
     *
     * @return the value of persontag_tbl.descs
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public String getDescs() {
        return descs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persontag_tbl.descs
     *
     * @param descs the value for persontag_tbl.descs
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public void setDescs(String descs) {
        this.descs = descs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persontag_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Persontag other = (Persontag) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getDescs() == null ? other.getDescs() == null : this.getDescs().equals(other.getDescs()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persontag_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getDescs() == null) ? 0 : getDescs().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persontag_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", descs=").append(descs);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}