package com.maiya.bean;

import java.io.Serializable;

public class Products implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_tbl.id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_tbl.brand
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_tbl.brand_type
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private Byte brandType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_tbl.price
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table products_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_tbl.id
     *
     * @return the value of products_tbl.id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_tbl.id
     *
     * @param id the value for products_tbl.id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_tbl.brand
     *
     * @return the value of products_tbl.brand
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_tbl.brand
     *
     * @param brand the value for products_tbl.brand
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_tbl.brand_type
     *
     * @return the value of products_tbl.brand_type
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public Byte getBrandType() {
        return brandType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_tbl.brand_type
     *
     * @param brandType the value for products_tbl.brand_type
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setBrandType(Byte brandType) {
        this.brandType = brandType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_tbl.price
     *
     * @return the value of products_tbl.price
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_tbl.price
     *
     * @param price the value for products_tbl.price
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Products other = (Products) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBrand() == null ? other.getBrand() == null : this.getBrand().equals(other.getBrand()))
            && (this.getBrandType() == null ? other.getBrandType() == null : this.getBrandType().equals(other.getBrandType()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBrand() == null) ? 0 : getBrand().hashCode());
        result = prime * result + ((getBrandType() == null) ? 0 : getBrandType().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", brand=").append(brand);
        sb.append(", brandType=").append(brandType);
        sb.append(", price=").append(price);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}