package com.maiya.bean;

import java.io.Serializable;

public class Promotion implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_tbl.id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_tbl.user_id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_tbl.user_image
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private String userImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_tbl.sets
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private String sets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_tbl.sets_id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private Long setsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table promotion_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_tbl.id
     *
     * @return the value of promotion_tbl.id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_tbl.id
     *
     * @param id the value for promotion_tbl.id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_tbl.user_id
     *
     * @return the value of promotion_tbl.user_id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_tbl.user_id
     *
     * @param userId the value for promotion_tbl.user_id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_tbl.user_image
     *
     * @return the value of promotion_tbl.user_image
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public String getUserImage() {
        return userImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_tbl.user_image
     *
     * @param userImage the value for promotion_tbl.user_image
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setUserImage(String userImage) {
        this.userImage = userImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_tbl.sets
     *
     * @return the value of promotion_tbl.sets
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public String getSets() {
        return sets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_tbl.sets
     *
     * @param sets the value for promotion_tbl.sets
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setSets(String sets) {
        this.sets = sets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_tbl.sets_id
     *
     * @return the value of promotion_tbl.sets_id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public Long getSetsId() {
        return setsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_tbl.sets_id
     *
     * @param setsId the value for promotion_tbl.sets_id
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    public void setSetsId(Long setsId) {
        this.setsId = setsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Promotion other = (Promotion) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserImage() == null ? other.getUserImage() == null : this.getUserImage().equals(other.getUserImage()))
            && (this.getSets() == null ? other.getSets() == null : this.getSets().equals(other.getSets()))
            && (this.getSetsId() == null ? other.getSetsId() == null : this.getSetsId().equals(other.getSetsId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserImage() == null) ? 0 : getUserImage().hashCode());
        result = prime * result + ((getSets() == null) ? 0 : getSets().hashCode());
        result = prime * result + ((getSetsId() == null) ? 0 : getSetsId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion_tbl
     *
     * @mbggenerated Sun Jul 08 13:04:45 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", userImage=").append(userImage);
        sb.append(", sets=").append(sets);
        sb.append(", setsId=").append(setsId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}