package com.maiya.bean;

import java.io.Serializable;

public class UserWithBLOBs extends User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.background_icon
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    private String backgroundIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.certificate
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    private String certificate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.background_icon
     *
     * @return the value of user_tbl.background_icon
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public String getBackgroundIcon() {
        return backgroundIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.background_icon
     *
     * @param backgroundIcon the value for user_tbl.background_icon
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public void setBackgroundIcon(String backgroundIcon) {
        this.backgroundIcon = backgroundIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.certificate
     *
     * @return the value of user_tbl.certificate
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public String getCertificate() {
        return certificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.certificate
     *
     * @param certificate the value for user_tbl.certificate
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public void setCertificate(String certificate) {
        this.certificate = certificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserWithBLOBs other = (UserWithBLOBs) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getConsultant() == null ? other.getConsultant() == null : this.getConsultant().equals(other.getConsultant()))
            && (this.getConsultantId() == null ? other.getConsultantId() == null : this.getConsultantId().equals(other.getConsultantId()))
            && (this.getPhoneNumber() == null ? other.getPhoneNumber() == null : this.getPhoneNumber().equals(other.getPhoneNumber()))
            && (this.getVerification() == null ? other.getVerification() == null : this.getVerification().equals(other.getVerification()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getAvatar() == null ? other.getAvatar() == null : this.getAvatar().equals(other.getAvatar()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getPrivilege() == null ? other.getPrivilege() == null : this.getPrivilege().equals(other.getPrivilege()))
            && (this.getPrivilegetype() == null ? other.getPrivilegetype() == null : this.getPrivilegetype().equals(other.getPrivilegetype()))
            && (this.getPoints() == null ? other.getPoints() == null : this.getPoints().equals(other.getPoints()))
            && (this.getIdentity() == null ? other.getIdentity() == null : this.getIdentity().equals(other.getIdentity()))
            && (this.getBackgroundIcon() == null ? other.getBackgroundIcon() == null : this.getBackgroundIcon().equals(other.getBackgroundIcon()))
            && (this.getCertificate() == null ? other.getCertificate() == null : this.getCertificate().equals(other.getCertificate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getConsultant() == null) ? 0 : getConsultant().hashCode());
        result = prime * result + ((getConsultantId() == null) ? 0 : getConsultantId().hashCode());
        result = prime * result + ((getPhoneNumber() == null) ? 0 : getPhoneNumber().hashCode());
        result = prime * result + ((getVerification() == null) ? 0 : getVerification().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getAvatar() == null) ? 0 : getAvatar().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getPrivilege() == null) ? 0 : getPrivilege().hashCode());
        result = prime * result + ((getPrivilegetype() == null) ? 0 : getPrivilegetype().hashCode());
        result = prime * result + ((getPoints() == null) ? 0 : getPoints().hashCode());
        result = prime * result + ((getIdentity() == null) ? 0 : getIdentity().hashCode());
        result = prime * result + ((getBackgroundIcon() == null) ? 0 : getBackgroundIcon().hashCode());
        result = prime * result + ((getCertificate() == null) ? 0 : getCertificate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", backgroundIcon=").append(backgroundIcon);
        sb.append(", certificate=").append(certificate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}