package com.maiya.bean;

import java.io.Serializable;
import java.util.List;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.id
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.name
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.consultant
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    private String consultant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.consultant_id
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    private Long consultantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.phone_number
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.verification
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    private String verification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.password
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.avatar
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.email
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.privilege
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    private String privilege;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.privilegetype
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    private Byte privilegetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.points
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    private Short points;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.identity
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    private Byte identity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    private static final long serialVersionUID = 1L;

    private List<Address> addresss;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.id
     *
     * @return the value of user_tbl.id
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.id
     *
     * @param id the value for user_tbl.id
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.name
     *
     * @return the value of user_tbl.name
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.name
     *
     * @param name the value for user_tbl.name
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.consultant
     *
     * @return the value of user_tbl.consultant
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public String getConsultant() {
        return consultant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.consultant
     *
     * @param consultant the value for user_tbl.consultant
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public void setConsultant(String consultant) {
        this.consultant = consultant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.consultant_id
     *
     * @return the value of user_tbl.consultant_id
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public Long getConsultantId() {
        return consultantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.consultant_id
     *
     * @param consultantId the value for user_tbl.consultant_id
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public void setConsultantId(Long consultantId) {
        this.consultantId = consultantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.phone_number
     *
     * @return the value of user_tbl.phone_number
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.phone_number
     *
     * @param phoneNumber the value for user_tbl.phone_number
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.verification
     *
     * @return the value of user_tbl.verification
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public String getVerification() {
        return verification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.verification
     *
     * @param verification the value for user_tbl.verification
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public void setVerification(String verification) {
        this.verification = verification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.password
     *
     * @return the value of user_tbl.password
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.password
     *
     * @param password the value for user_tbl.password
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.avatar
     *
     * @return the value of user_tbl.avatar
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.avatar
     *
     * @param avatar the value for user_tbl.avatar
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.email
     *
     * @return the value of user_tbl.email
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.email
     *
     * @param email the value for user_tbl.email
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.privilege
     *
     * @return the value of user_tbl.privilege
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public String getPrivilege() {
        return privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.privilege
     *
     * @param privilege the value for user_tbl.privilege
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public void setPrivilege(String privilege) {
        this.privilege = privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.privilegetype
     *
     * @return the value of user_tbl.privilegetype
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public Byte getPrivilegetype() {
        return privilegetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.privilegetype
     *
     * @param privilegetype the value for user_tbl.privilegetype
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public void setPrivilegetype(Byte privilegetype) {
        this.privilegetype = privilegetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.points
     *
     * @return the value of user_tbl.points
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public Short getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.points
     *
     * @param points the value for user_tbl.points
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public void setPoints(Short points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.identity
     *
     * @return the value of user_tbl.identity
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public Byte getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.identity
     *
     * @param identity the value for user_tbl.identity
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    public void setIdentity(Byte identity) {
        this.identity = identity;
    }

    public List<Address> getAddresss() {
        return addresss;
    }

    public void setAddresss(List<Address> addresss) {
        this.addresss=addresss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getConsultant() == null ? other.getConsultant() == null : this.getConsultant().equals(other.getConsultant()))
            && (this.getConsultantId() == null ? other.getConsultantId() == null : this.getConsultantId().equals(other.getConsultantId()))
            && (this.getPhoneNumber() == null ? other.getPhoneNumber() == null : this.getPhoneNumber().equals(other.getPhoneNumber()))
            && (this.getVerification() == null ? other.getVerification() == null : this.getVerification().equals(other.getVerification()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getAvatar() == null ? other.getAvatar() == null : this.getAvatar().equals(other.getAvatar()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getPrivilege() == null ? other.getPrivilege() == null : this.getPrivilege().equals(other.getPrivilege()))
            && (this.getPrivilegetype() == null ? other.getPrivilegetype() == null : this.getPrivilegetype().equals(other.getPrivilegetype()))
            && (this.getPoints() == null ? other.getPoints() == null : this.getPoints().equals(other.getPoints()))
            && (this.getIdentity() == null ? other.getIdentity() == null : this.getIdentity().equals(other.getIdentity()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getConsultant() == null) ? 0 : getConsultant().hashCode());
        result = prime * result + ((getConsultantId() == null) ? 0 : getConsultantId().hashCode());
        result = prime * result + ((getPhoneNumber() == null) ? 0 : getPhoneNumber().hashCode());
        result = prime * result + ((getVerification() == null) ? 0 : getVerification().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getAvatar() == null) ? 0 : getAvatar().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getPrivilege() == null) ? 0 : getPrivilege().hashCode());
        result = prime * result + ((getPrivilegetype() == null) ? 0 : getPrivilegetype().hashCode());
        result = prime * result + ((getPoints() == null) ? 0 : getPoints().hashCode());
        result = prime * result + ((getIdentity() == null) ? 0 : getIdentity().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbg.generated Sun Jul 08 14:51:08 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", consultant=").append(consultant);
        sb.append(", consultantId=").append(consultantId);
        sb.append(", phoneNumber=").append(phoneNumber);
        sb.append(", verification=").append(verification);
        sb.append(", password=").append(password);
        sb.append(", avatar=").append(avatar);
        sb.append(", email=").append(email);
        sb.append(", privilege=").append(privilege);
        sb.append(", privilegetype=").append(privilegetype);
        sb.append(", points=").append(points);
        sb.append(", identity=").append(identity);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append(", addresss=").append(addresss);
        sb.append("]");
        return sb.toString();
    }
}